### ISSUE TITLE
オフラインのときはネットワークアクセスしないようにしてほしい

### ISSUE THREAD

**Issue by irok** [irok/KinnosukeTimeRecorder#5]
バックグラウンドで定期的にサーバにアクセスしてるっぽくて（なんでか忘れた）、オフラインの時にエラーでまくるので何とかしたい。

**Comment by kimromi** [comment]
あー、、たぶん僕が入れた機能で5分ごとに接続しようとしてるからですね。。:bow: 
https://github.com/kimromi/KinnosukeTimeRecorder/pull/1/files
なんとかします！

**Comment by irok** [comment]
おっと、そうでしたか。（全然見れてませんでした。）
この辺使えばいいのかなーとぼんやり考えてました。
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events

**Comment by kimromi** [comment]
@irok プルリクだしておきました〜。確認お願いいたします。
https://github.com/irok/KinnosukeTimeRecorder/pull/7

**Comment by irok** [comment]
@kimromi ご対応ありがとうございます。取り込んでウェブストアに公開しました！

**Comment by kimromi** [comment]
ありがとうございます！:bow:
