### ISSUE TITLE
gulp4に上げる

### ISSUE THREAD

**Issue by irok** [irok/KinnosukeTimeRecorder#9]
利用している event-stream には脆弱性があり、警告の対象となっているため、gulp4にアップデートして event-stream を排除する。

**Comment by kimromi** [comment]
https://github.com/irok/KinnosukeTimeRecorder/pull/25 で対応してみましたのでお暇なときにでも見てみてください。

**Comment by irok** [comment]
@kimromi ありがとうございます！マージさせて頂きました。

**Comment by kimromi** [comment]
ありがとうございますー！
